{
 "title": "K3s Volume Utilization",
 "tags": [
  "kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Volume Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum (kubelet_volume_stats_available_bytes{namespace=~\"$Namespace\"}) / sum (kubelet_volume_stats_capacity_bytes{namespace=~\"$Namespace\"})) * 100"
    }
   ]
  },
  {
   "title": "Volume Utilization",
   "type": "timeseries",
   "description": "Shows the utilization of provisioned volumes in percentage",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1- kubelet_volume_stats_available_bytes{namespace=~\"$Namespace\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$Namespace\"}) * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kubelet_volume_stats_used_bytes{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kubelet_volume_stats_capacity_bytes{namespace=~\"$Namespace\"})"
    }
   ]
  }
 ]
}